version: '3'

services:
  db:
    container_name: db
    image: mongo:4.4.2
    restart: always
    volumes: 
      - ./db-volume:/data/db
    expose:
      - 27017

  backend:
    container_name: backend
    build: ./backend/
    expose: 
      - 3001
    ports:
      - 3001:3001
    restart: always

  frontend:
    container_name: frontend
    build: ./frontend/
    ports: 
    - 3000:3000
    restart: always
  
  bot:
    container_name: bot
    build: ./bot/
    restart: always